"""NSFW 违禁词过滤"""
import re

# 英文单词级关键词（用词边界 \b 匹配，避免 ass 匹配到 class/glass 等）
_EN_WORDS = [
    # --- 原有 ---
    "nsfw", "nude", "naked", "topless", "bottomless",
    "nipple", "nipples", "pussy", "vagina", "penis", "dick", "cock",
    "clitoris", "clit", "vulva", "labia", "urethra", "foreskin", "scrotum",
    "sex", "sexual", "intercourse", "penetration", "cum", "cumshot",
    "creampie", "bukkake", "facial", "deepthroat",
    "blowjob", "handjob", "footjob", "titjob", "boobjob", "paizuri",
    "fellatio", "cunnilingus", "rimjob", "analingus",
    "masturbation", "masturbating", "orgasm", "erotic", "hentai", "ahegao",
    "bondage", "bdsm", "tentacle", "rape", "gangbang", "orgy", "threesome",
    "ass", "anus", "butthole", "asshole", "rectum",
    "groping", "undress", "strip", "fondle", "molest",
    "exposed", "genitals", "pubic", "crotch", "groin",
    "ejaculation", "squirt", "squirting", "arousal",
    "dominatrix", "submissive", "sadism", "masochism", "fetish",
    "incest", "bestiality", "zoophilia", "necrophilia",
    "loli", "shota", "underage", "pedophile",
    "dildo", "vibrator", "buttplug", "fleshlight",
    "shibari", "gagged", "blindfold", "collar", "leash",
    "enema", "fisting", "pegging", "prolapse",
    "cameltoe", "upskirt", "downblouse",
    "pornography", "porn", "xxx", "r18",
    # --- 从 swearList.csv 新增（已去重）---
    "anal", "arrse", "arse", "assfucker", "assfukka", "assholes", "asswhole",
    "ballbag", "balls", "ballsack", "bastard", "bellend",
    "biatch", "bitch", "bitcher", "bitchers", "bitches", "bitchin", "bitching",
    "bloody", "bollock", "bollok", "boner", "boob", "boobs",
    "breast", "breasts", "buceta", "bugger", "bum", "butt", "buttmuch",
    "chink", "clits", "cnut",
    "cockface", "cockhead", "cockmunch", "cockmuncher", "cocks",
    "cocksuck", "cocksucked", "cocksucker", "cocksucking", "cocksucks",
    "cok", "cokmuncher", "coksucka", "coon", "cox", "crap",
    "cummer", "cumming", "cums", "cunilingus", "cunillingus",
    "cunt", "cuntlick", "cuntlicker", "cuntlicking", "cunts",
    "damn", "dickhead", "dildos", "dink", "dinks", "dirsa",
    "dogging", "donkeyribber", "doosh", "duche", "dyke",
    "ejaculate", "ejaculated", "ejaculates", "ejaculating", "ejaculatings", "ejakulate",
    "fag", "fagging", "faggitt", "faggot", "faggs", "fagot", "fagots", "fags",
    "fanny", "fannyflaps", "fannyfucker", "fatass",
    "fcuk", "fcuker", "fcuking", "feck", "fecker",
    "felching", "fellate",
    "fingerfuck", "fingerfucked", "fingerfucker", "fingerfuckers", "fingerfucking", "fingerfucks",
    "fistfuck", "fistfucked", "fistfucker", "fistfuckers", "fistfucking", "fistfuckings", "fistfucks",
    "flange", "fook", "fooker",
    "fuck", "fucka", "fucked", "fucker", "fuckers", "fuckhead", "fuckheads",
    "fuckin", "fucking", "fuckings", "fucks", "fuckwhit", "fuckwit",
    "fuk", "fuker", "fukker", "fukkin", "fuks", "fukwhit", "fukwit", "fux",
    "gaylord", "gaysex", "goatse",
    "hell", "hoar", "hoare", "hoer", "homo", "hore", "horniest", "horny", "hotsex",
    "jackoff", "jap", "jism", "jiz", "jizm", "jizz",
    "kawk", "knob", "knobead", "knobed", "knobend", "knobhead", "knobjocky", "knobjokey",
    "kock", "kondum", "kondums", "kum", "kummer", "kumming", "kums", "kunilingus",
    "lmfao", "lust", "lusting",
    "masochist", "masterb8", "masterbate", "masterbation", "masterbations", "masturbate",
    "mofo", "mothafuck", "mothafucka", "mothafuckas", "mothafuckaz",
    "mothafucked", "mothafucker", "mothafuckers", "mothafuckin", "mothafucking", "mothafuckings", "mothafucks",
    "motherfuck", "motherfucked", "motherfucker", "motherfuckers",
    "motherfuckin", "motherfucking", "motherfuckings", "motherfuckka", "motherfucks",
    "muff", "mutha", "muthafecker", "muthafuckker", "muther", "mutherfucker",
    "nazi", "nigga", "niggah", "niggas", "niggaz", "nigger", "niggers",
    "nob", "nobhead", "nobjocky", "nobjokey", "numbnuts", "nutsack",
    "orgasim", "orgasims", "orgasms",
    "pawn", "pecker", "penisfucker", "phonesex",
    "phuck", "phuk", "phuked", "phuking", "phukked", "phukking", "phuks", "phuq",
    "pigfucker", "pimpis", "piss", "pissed", "pisser", "pissers", "pisses",
    "pissflaps", "pissin", "pissing", "pissoff", "poop",
    "porno", "pornos", "prick", "pricks", "pron", "pube",
    "pusse", "pussi", "pussies", "pussys",
    "retard", "rimjaw", "rimming",
    "sadist", "schlong", "screwing", "scroat", "scrote", "scrotum", "semen",
    "shag", "shagger", "shaggin", "shagging", "shemale",
    "shit", "shitdick", "shite", "shited", "shitey", "shitfuck", "shitfull",
    "shithead", "shiting", "shitings", "shits", "shitted", "shitter", "shitters",
    "shitting", "shittings", "shitty",
    "skank", "slut", "sluts", "smegma", "smut", "snatch",
    "spac", "spunk",
    "testical", "testicle", "tit", "titfuck", "tits", "titt",
    "tittiefucker", "titties", "tittyfuck", "tittywank", "titwank",
    "tosser", "turd", "twat", "twathead", "twatty", "twunt", "twunter",
    "vaginal", "viagra", "wang", "wank", "wanker", "wanky",
    "whoar", "whore", "willies", "willy", "xrated",
    # --- swearList.csv 中的特殊术语 ---
    "clitoral", "phallic", "perineum", "intravaginal",
    "tonguejob", "tentaclejob", "glansjob", "glans", "tailjob", "shoejob",
    "sexually", "underwear", "menstruation", "menstrual",
    "erotibot", "pervert", "cleavage", "futa", "furry",
    "panties", "lingerie", "condom", "strips", "insertion",
    "peeing", "pee", "peeping", "erection", "yaoi",
    "cumdrip", "precum", "defloration", "netorare", "irrumatio",
    "spitroast", "tribadism", "impregnation", "frottage", "fertilization",
    "voyeurism", "anilingus", "newhalf", "futasub", "afterglow",
    "cumdump", "aroused", "naizuri", "autofacial",
    "autoarousal", "lolidom", "koonago", "aphrodisiac", "scat",
    "autofellatio", "pecjob", "autopaizuri", "aneros", "codpiece",
    "reichsadler", "bootjob", "oral", "tentacles", "fingering",
    "gaping", "phimosis", "ryona", "hairjob",
    "drugs", "drugged", "wax", "nakadashi",
    "pregnancy", "areola", "areolae",
]
